### ISSUE TITLE
make test error?

### ISSUE THREAD

**Issue by teleger** [chengyangfu/caffe#13]
我的caffe ssd版本，都能够成功编译。dssd的版本就make all - j4是没有问题的。make test. 就出错了。我的电脑操作系统是16.04.显存为2 gb.  错误地点:I CPUBBoxUtilTest_TestComputeConfLoss_Test::TestBody()

**Comment by chengyangfu** [comment]
There are some errors caused when I try to synchronize the new codes from Wei's repository. 
I may upload another repository in PyTorch later.
